language: php

matrix:
  include:
    - php: 5.6
      env:
        - RABBITMQ_HOST=127.0.0.1
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=guest
        - RABBITMQ_PASSWORD=guest
        - RABBITMQ_VHOST=/
    - php: 7.0
      env:
        - RABBITMQ_HOST=127.0.0.1
        - RABBITMQ_PORT=5672
        - RABBITMQ_USER=guest
        - RABBITMQ_PASSWORD=guest
        - RABBITMQ_VHOST=/

services:
  - rabbitmq

before_script:
  - composer selfupdate

install:
  - composer install

script:
  - bin/phpspec run
  - bin/behat
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover clover.xml