#!/usr/bin/env php
<?php

use Domain\Task\Task;
use Infrastructure\AmqpLib\v26\RabbitMQ\Task\Consumer;
use Infrastructure\AmqpLib\v26\RabbitMQ\Task\Producer;
use Infrastructure\Logger\NaiveStdoutLogger;

require_once '/app/queues/vendor/autoload.php';

$logger = new NaiveStdoutLogger();

//produce
$producer = new Producer(
    getenv('RABBITMQ_HOST'),
    getenv('RABBITMQ_PORT'),
    getenv('RABBITMQ_USER'),
    getenv('RABBITMQ_PASSWORD'),
    getenv('RABBITMQ_VHOST'),
    'test2',
    $logger
);
$producer->add(new Task('direct1', array(1,2,3,4,5)));
$producer->produce();


//consume
$consumer = new Consumer(
    getenv('RABBITMQ_HOST'),
    getenv('RABBITMQ_PORT'),
    getenv('RABBITMQ_USER'),
    getenv('RABBITMQ_PASSWORD'),
    getenv('RABBITMQ_VHOST'),
    'test2',
    'test',
    $logger
);
try {
    $consumer->consume(function(Task $task){
        var_dump($task);
    },2);
} catch(\Exception $e) {}