#!/usr/bin/env php
<?php

use Domain\Task\Task;
use Infrastructure\AmqpLib\v26\RabbitMQ\Task\Consumer;
use Infrastructure\Logger\NaiveStdoutLogger;

require_once '/app/queues/vendor/autoload.php';

$logger = new NaiveStdoutLogger();

$consumer = new Consumer(
    'rabbitmq',
    5672,
    'guest',
    'guest',
    '/',
    'test',
    'test',
    $logger
);
$consumer->consume(function(Task $message) {
    var_dump($message);
});