#!/usr/bin/env php
<?php

require_once '../vendor/autoload.php';
require_once '../metrics.php';

if (!isset($argv[1])) {
    echo "usage: produce <id>" . PHP_EOL;
    exit(1);
}

$id = $argv[1];

$logger = new \Cmp\Queue\Infrastructure\Log\NullLogger();

$config = new Cmp\Queue\Infrastructure\RabbitMQ\RabbitMQConfig(getenv('QUEUES_RABBITMQ_HOST'), getenv('QUEUES_RABBITMQ_PORT'), getenv('QUEUES_RABBITMQ_USER'), getenv('QUEUES_RABBITMQ_PASS'), getenv('QUEUES_RABBITMQ_TASKS_EXCHANGE'));

$producer = new \Cmp\Task\Infrastructure\Producer\RabbitMQ\Producer($config, $logger);

$task1 = new \Cmp\Task\Domain\Task\Task($id, ['somekey' => 'Request']);

$monitor->increment('queues.testhelper.task.producing');
$producer->add($task1);
$producer->produce();
$monitor->increment('queues.testhelper.task.produced');