#!/usr/bin/env php
<?php

use Domain\Task\Task;
use Infrastructure\AmqpLib\v26\RabbitMQ\Task\Producer;
use Infrastructure\Logger\NaiveStdoutLogger;

require_once '/app/queues/vendor/autoload.php';

$logger = new NaiveStdoutLogger();

$producer = new Producer(
    'rabbitmq',
    5672,
    'guest',
    'guest',
    '/',
    'test',
    $logger
);

$producer->add(new Task('direct1', array(1,2,3,4,5)));
//$producer->add(new Task('10sec', array(1,2,3,4,5), 10));
//$producer->add(new Task('5sec', array(1,2,3,4,5), 5));
$producer->add(new Task('direct2', array(1,2,3,4,5)));
$producer->produce();