#!/usr/bin/env php
<?php

require_once '../vendor/autoload.php';
require_once '../metrics.php';

if (!isset($argv[1]) || !isset($argv[2])) {
    echo "usage: publish <origin> <name>" . PHP_EOL;
    exit(1);
}

$origin = $argv[1];
$name = $argv[2];
$ocurredOn = microtime(true);

$logger = new \Cmp\Queue\Infrastructure\Log\NullLogger();

$config = new Cmp\Queue\Infrastructure\RabbitMQ\RabbitMQConfig(getenv('QUEUES_RABBITMQ_HOST'), getenv('QUEUES_RABBITMQ_PORT'), getenv('QUEUES_RABBITMQ_USER'), getenv('QUEUES_RABBITMQ_PASS'), getenv('QUEUES_RABBITMQ_DOMAINEVENTS_EXCHANGE'));

$publisher = new Cmp\DomainEvent\Infrastructure\Publisher\RabbitMQ\Publisher($config, $logger);


$domainEvent1 = new Cmp\DomainEvent\Domain\Event\DomainEvent($origin, $name, $ocurredOn, ['extraData1' => 'extraValue1', 'extraData2' => 'extraValue2']);

$monitor->increment('queues.testhelper.domainevent.publishing');
$publisher->add($domainEvent1);
$publisher->publish();
$monitor->increment('queues.testhelper.domainevent.published');