#!/usr/bin/env php
<?php

require_once '../vendor/autoload.php';
require_once '../metrics.php';

if (!isset($argv[1]) || !isset($argv[2])) {
    echo "usage: subscribe <delay> <domainTopic1> <domainTopic2> ..." . PHP_EOL;
    exit(1);
}

$delay = $argv[1];
$domainTopics = array_slice($argv, 2);

class TestEventSubscriptor implements \Cmp\DomainEvent\Domain\Event\EventSubscriptor
{

    private $monitor;
    private $delay;

    public function __construct(\Cmp\Application\Monitoring\Monitor $monitor, $delay)
    {
        $this->monitor = $monitor;
        $this->delay = $delay;
    }

    public function notify(\Cmp\DomainEvent\Domain\Event\DomainEvent $event)
    {
        $this->monitor->increment('queues.testhelper.domainevent.notified');
        var_dump($event);
        sleep($this->delay);
    }

    public function isSubscribed(\Cmp\DomainEvent\Domain\Event\DomainEvent $event)
    {
        return true;
    }
}

$logger = new \Cmp\DomainEvent\Infrastructure\Log\NullLogger();

$config = new Cmp\Queue\Infrastructure\RabbitMQ\RabbitMQConfig(getenv('QUEUES_RABBITMQ_HOST'), getenv('QUEUES_RABBITMQ_PORT'), getenv('QUEUES_RABBITMQ_USER'), getenv('QUEUES_RABBITMQ_PASS'), getenv('QUEUES_RABBITMQ_DOMAINEVENTS_EXCHANGE'), getenv('QUEUES_RABBITMQ_DOMAINEVENTS_QUEUE'));

$subscriber = new \Cmp\DomainEvent\Application\Subscriber\Subscriber($config, $domainTopics, $logger);

$testEventSubscriptor = new TestEventSubscriptor($monitor, $delay);

$subscriber->subscribe($testEventSubscriptor);

$subscriber->start();