#!/usr/bin/env php
<?php

use Cmp\Queues\Domain\Event\DomainEvent;
use Cmp\Queues\Infrastructure\AmqpLib\v26\RabbitMQ\DomainEvent\Publisher;
use Cmp\Queues\Infrastructure\Logger\NaiveStdoutLogger;

require_once '../../../../../vendor/autoload.php';

$logger = new NaiveStdoutLogger();

$publisher = new Publisher(
    getenv('RABBITMQ_HOST'),
    getenv('RABBITMQ_PORT'),
    getenv('RABBITMQ_USER'),
    getenv('RABBITMQ_PASSWORD'),
    getenv('RABBITMQ_VHOST'),
    'test-domain-event',
    $logger
);

$publisher->add(new DomainEvent('queues.helper', 'test', '1.0.0', microtime(true), array(1,2,3,4,5)));
$publisher->publish();